name: Not Alone
description: This contains a nice description of the site.
logo: logo.png

markdown: kramdown
pygments: true

baseurl: /campus

kramdown:
  parse_block_html: true

cachebuster: '0426131729'